# Github action to build Jekyll site for a pull request preview
#
#  Built site is pushed to 'gh-pages' branch
#   under directory pr/pr_id/
#

name: Jekyll PR Preview

on:
  issue_comment:
    types: [created]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages
  SITE_URL: https://fortran-lang.org
  FPM_INDEX: "https://raw.githubusercontent.com/fortran-lang/fpm-registry/master/index.json"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body,'#build_preview')
    
    steps:

    # Checkout PR branch into SRC_DIR
    - name: Checkout pr/${{github.event.issue.number}}
      run: | 
        git clone https://github.com/${{github.repository}} ${{env.SRC_DIR}}
        cd ${{env.SRC_DIR}}
        git fetch origin pull/${{github.event.issue.number}}/head:pr-${{github.event.issue.number}}
        git checkout pr-${{github.event.issue.number}}
    
    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ${{env.PUBLISH_DIR}}
        ref: 'gh-pages' 
    
    # Install ruby 2.7.x
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    # Setup Jekyll in SRC_DIR
    - name: Setup Jekyll
      run: |
        cd ${{env.SRC_DIR}}
        sudo gem install bundler
        bundle config path .bundle
        bundle install
    
    # Sets Jekyll output directory using PR id
    - name: Define output directory
      run: echo "BUILD_DIR=pr/${{github.event.issue.number}}" >> $GITHUB_ENV

    # Appends PR-based output directory to Jekyll baseurl variable
    - name: Update Jekyll site config
      run: |
        cd ${{env.SRC_DIR}}
        grep baseurl _config.yml|grep -v "#" |awk -F : '{print $2}' | xargs > base_url
        sed -i '/baseurl:/d' _config.yml
        echo "baseurl: $(cat base_url)/${{env.BUILD_DIR}}" >> _config.yml
        echo "pull_request: ${{github.event.issue.number}}" >> _config.yml
    
    # Download latest fpm-registry index
    - name: Download fpm-registry index
      run: |
        cd ${{env.SRC_DIR}}/_data
        wget ${{env.FPM_INDEX}}
        mv index.json fpm_registry_index.json

    # Run Jekyll build and copy output to PUBLISH_DIR
    - name: Build Jekyll Site
      run: |
        cd ${{env.SRC_DIR}}
        bundle exec jekyll build --future -d _site/${BUILD_DIR}
        cp -r _site/* ../${{env.PUBLISH_DIR}}/
        touch ../${{env.PUBLISH_DIR}}/.nojekyll

    # Commit and push changes to remote/gh-pages
    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@v4.4.0
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "Jekyll build, preview ${{env.BUILD_DIR}} (on:pull_request)"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Comment on pull request 
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{github.event.issue.number}}
        body: "This PR has been built with Jekyll and can be previewed at: <${{env.SITE_URL}}/${{env.BUILD_DIR}}/>"

